### ISSUE TITLE
Using custom prefix exceptions

### ISSUE THREAD

**Issue by gorango** [wooorm/parse-latin#28]
Certain texts can contain abbreviations that are not captured by the [regex tests](https://github.com/wooorm/parse-latin/blob/main/lib/plugin/merge-prefix-exceptions.js#L6-L22). 

I'm curious if this might be worth adding as an option on the constructor - instead of having to rely on extending the plugins (the way [`ParseEnglish`](https://github.com/wooorm/parse-english) does):

```js
class ParseEnglish extends ParseLatin {}

ParseEnglish.prototype.tokenizeParagraphPlugins = [
  modifyChildren(mergeEnglishPrefixExceptions)
].concat(ParseEnglish.prototype.tokenizeParagraphPlugins)
```

I was originally going to open an issue on the parse-english repo but I thought it might be worth exploring the option here for a few reasons:
- `ParseLatin` can be reliably used for most European languages with abbreviations being the main barrier to accurate sentence tokenization.
- Exceptions can be supplied as a string array - providing a simpler interface for i18n support of out the box.

I'm not sure if the juice is worth the squeeze for a feature like this (especially since a solution exists). But it may be worthwhile to expose the [`mergePrefixExceptions`](https://github.com/wooorm/parse-latin/blob/0ee7c5e945671020d040ec7e31f90ad106db9db1/lib/plugin/merge-prefix-exceptions.js?_pjax=%23js-repo-pjax-container%3Afirst-of-type%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%3Afirst-of-type%2C%20%5Bdata-pjax-container%5D%3Afirst-of-type#L26) function and to document this particular use case for others in the future.

**Comment by wooorm** [comment]
Thanks for your patience.
I am open to such an API. Preferrably as discussed a clean, shared, API that works with the different projects.
I am closing this though, as I think it’s a nice to have, that I personally am not currently interested in working on!
But, let me know if you (or someone else?) is interested in working on this!
